# Generated by Django 5.2.1 on 2025-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='favourite',
            name='cuisine',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='favourite',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='favourite',
            name='name',
            field=models.CharField(default='Unknown Meal', max_length=200),
        ),
        migrations.AddField(
            model_name='favourite',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='favourite',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
